default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres


development:
  primary: &primary_development
    <<: *default
    database: r_packages_development
  queue:
    <<: *primary_development
    database: r_packages_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: r_packages_test

production:
  primary: &primary_production
    <<: *default
    database: r_packages_production
    username: r_packages
    password: <%= ENV["R_PACKAGES_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: r_packages_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: r_packages_production_queue
    migrations_paths: db/queue_migrate
